version: "3.7"

services:
  # app:
  #   container_name: angular_app1_node
  #   build:
  #     context: .
  #     dockerfile: ./docker/development/node/Dockerfile
  #   volumes:
  #     - ./app:/srv/app
  #     - ./app/node_modules:/srv/app/node_modules
  #     - /etc/localtime:/etc/localtime:ro
  #   ports:
  #     - "8002:4200"
  #   restart: unless-stopped
  #   environment:
  #     - NODE_ENV=development
  #   command: "ng build --watch"

  server:
    # image: nginx:alpine
    container_name: angular_app1_nginx
    working_dir: /srv/app
    build:
      context: .
      dockerfile: ./docker/development/nginx/Dockerfile
    volumes:
      - ./app/dist/qualis-mf-app1:/srv/app
      - ./docker/development/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/development/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "8082:80"
    # depends_on:
    #   - app
    # links:
    #   - app