version: "3.7"

services:
  app:
    container_name: angular_app_navibar_node
    build:
      context: .
      dockerfile: ./docker/development/node/Dockerfile
    volumes:
      - ./app:/srv/app
      - ./app/node_modules:/srv/app/node_modules
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "8000:4200"
    restart: unless-stopped
    environment:
      - NODE_ENV=development
    command: "npm start"

  server:
    # image: nginx:alpine
    container_name: angular_app_navibar_nginx
    working_dir: /srv/app
    build:
      context: .
      dockerfile: ./docker/development/nginx/Dockerfile
    volumes:
      - ./app/dist:/srv/app
      - ./docker/development/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/development/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "8082:80"
    depends_on:
      - app
    links:
      - app